import type {
  Activity,
  Donation,
  Evidence,
  InventoryTransaction,
  Nursery,
  PlantingEvent,
  Program,
  Sale,
  SeedBatch,
  Seedbed,
  Species,
  SurvivalObservation,
  Transfer,
  Verification,
  CfaState,
} from "./types";

const DAY = 24 * 60 * 60 * 1000;

function ago(days: number, hours = 0) {
  return new Date(Date.now() - days * DAY - hours * 60 * 60 * 1000).toISOString();
}

function dayOf(daysAgo: number) {
  return new Date(Date.now() - daysAgo * DAY).toISOString().slice(0, 10);
}

const species: Species[] = [
  {
    id: "SP-PRUNUS",
    commonName: "Prunus africana",
    scientificName: "Prunus africana",
    localNames: ["Pygeum", "Mueri"],
    category: "INDIGENOUS",
    use: "MEDICINAL",
    growthNotes: "Slow growing, prefers well-drained loam above 1500m.",
    isActive: true,
  },
  {
    id: "SP-VITEX",
    commonName: "Vitex keniensis",
    scientificName: "Vitex keniensis",
    localNames: ["Mukima", "Mlalame"],
    category: "INDIGENOUS",
    use: "TIMBER",
    growthNotes: "Fast straight-growing pioneer, tolerates poor soils.",
    isActive: true,
  },
  {
    id: "SP-CROTON",
    commonName: "Croton megalocarpus",
    scientificName: "Croton megalocarpus",
    localNames: ["Mumumu", "Mukoroso"],
    category: "INDIGENOUS",
    use: "AGROFORESTRY",
    growthNotes: "Fixes nitrogen, good boundary tree, seeds recalcitrant.",
    isActive: true,
  },
  {
    id: "SP-DOMBEYA",
    commonName: "Dombeya torrida",
    scientificName: "Dombeya torrida",
    localNames: ["Kikuyu", "Cheptanduu"],
    category: "INDIGENOUS",
    use: "RIPARIAN",
    growthNotes: "Riparian buffer species, needs reliable moisture.",
    isActive: true,
  },
  {
    id: "SP-GREVILLEA",
    commonName: "Grevillea robusta",
    scientificName: "Grevillea robusta",
    localNames: ["Silky oak"],
    category: "EXOTIC",
    use: "FODDER",
    growthNotes: "Fast fodder and shade tree, widely available.",
    isActive: true,
  },
  {
    id: "SP-TERMINALIA",
    commonName: "Terminalia superba",
    scientificName: "Terminalia superba",
    localNames: ["Musanga"],
    category: "INDIGENOUS",
    use: "TIMBER",
    growthNotes: "High-value timber, needs spacing of 3m or more.",
    isActive: true,
  },
];

const nurseries: Nursery[] = [
  {
    id: "NUR-KAPSABET",
    cfaId: "CFA-KE-042",
    name: "Kapsabet Central Nursery",
    county: "Nandi",
    subCounty: "Kapsabet",
    ward: "Kapsabet",
    community: "Chepterit",
    location: "Chepterit trading centre, 2km along Kericho road",
    latitude: -0.2027,
    longitude: 35.1021,
    managerName: "Achieng",
    contactPhone: "+254700000001",
    establishedAt: dayOf(2200),
    nurseryType: "PROPAGATION",
    waterSource: "Borehole with 5,000L header tank",
    capacity: 20000,
    status: "ACTIVE",
    notes: "Main production nursery handling Prunus, Vitex and Croton.",
  },
  {
    id: "NUR-KAPTAGAT",
    cfaId: "CFA-KE-042",
    name: "Kaptagat Riparian Nursery",
    county: "Nandi",
    subCounty: "Kapsabet",
    ward: "Kaptagat",
    community: "Kaptagat",
    location: "Kaptagat river bank, adjacent to the buffer",
    latitude: -0.3155,
    longitude: 35.0112,
    managerName: "Kiptoo",
    contactPhone: "+254700000002",
    establishedAt: dayOf(900),
    nurseryType: "NURSERY",
    waterSource: "River abstraction, seasonal",
    capacity: 8000,
    status: "ACTIVE",
    notes: "Supplies riparian buffer species only.",
  },
];

const seedbeds: Seedbed[] = [
  {
    id: "SB-KC-A",
    nurseryId: "NUR-KAPSABET",
    name: "Seedbed A",
    locationInNursery: "North terrace",
    establishedAt: dayOf(700),
    capacity: 6000,
    propagationMethod: "NURSERY_BED",
    status: "ACTIVE",
    managerName: "Achieng",
  },
  {
    id: "SB-KC-B",
    nurseryId: "NUR-KAPSABET",
    name: "Seedbed B",
    locationInNursery: "East terrace",
    establishedAt: dayOf(540),
    capacity: 5000,
    propagationMethod: "CONTAINER",
    status: "ACTIVE",
    managerName: "Achieng",
  },
  {
    id: "SB-KC-C",
    nurseryId: "NUR-KAPSABET",
    name: "Seedbed C",
    locationInNursery: "Hardening area",
    establishedAt: dayOf(300),
    capacity: 3000,
    propagationMethod: "DIRECT_SOWING",
    status: "MAINTENANCE",
    managerName: "Kiptoo",
    notes: "Under re-preparation after water damage.",
  },
  {
    id: "SB-KT-A",
    nurseryId: "NUR-KAPTAGAT",
    name: "Kaptagat bed A",
    locationInNursery: "Riverside plot",
    establishedAt: dayOf(400),
    capacity: 4000,
    propagationMethod: "NURSERY_BED",
    status: "ACTIVE",
    managerName: "Kiptoo",
  },
];

const batches: SeedBatch[] = [
  {
    id: "BATCH-2026-01",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-PRUNUS",
    seedSource: "Collected from mother trees in Chepterit forest",
    collectionLocation: "Chepterit forest block",
    collectionDate: dayOf(210),
    acquiredAt: dayOf(205),
    quantityAcquired: 2000,
    treatmentMethod: "Fresh, no treatment",
    storageLocation: "Seed store, shelf 1",
    responsibleUser: "Achieng",
    status: "EXHAUSTED",
  },
  {
    id: "BATCH-2026-02",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-CROTON",
    seedSource: "Purchased from Kenya Forestry Seed Centre",
    collectionLocation: "KFS Kitale",
    collectionDate: dayOf(150),
    acquiredAt: dayOf(148),
    quantityAcquired: 3000,
    treatmentMethod: "Hot water treatment 5 min",
    storageLocation: "Seed store, shelf 2",
    responsibleUser: "Kiptoo",
    status: "IN_PRODUCTION",
  },
  {
    id: "BATCH-2026-03",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-DOMBEYA",
    seedSource: "Collected from riparian mother trees",
    collectionLocation: "Kaptagat river reserve",
    collectionDate: dayOf(120),
    acquiredAt: dayOf(118),
    quantityAcquired: 1200,
    treatmentMethod: "Shade drying then cold storage",
    storageLocation: "Kaptagat store",
    responsibleUser: "Kiptoo",
    status: "IN_PRODUCTION",
  },
];

type TxnSeed = [
  id: string,
  transactionType: InventoryTransaction["transactionType"],
  nurseryId: string,
  speciesId: string,
  quantity: number,
  daysAgo: number,
  source: string,
  extra?: Partial<InventoryTransaction>,
];

function txn([
  id,
  transactionType,
  nurseryId,
  speciesId,
  quantity,
  daysAgo,
  source,
  extra,
]: TxnSeed): InventoryTransaction {
  return {
    id,
    transactionType,
    nurseryId,
    speciesId,
    quantity,
    direction: extra?.direction ?? "IN",
    date: dayOf(daysAgo),
    source,
    recordedBy: extra?.recordedBy ?? "Achieng",
    verificationStatus: extra?.verificationStatus ?? "VERIFIED",
    createdAt: ago(daysAgo),
    ...extra,
  };
}

const transactions: InventoryTransaction[] = [
  // Kapsabet — Prunus
  txn(["TX-0001", "OPENING_STOCK", "NUR-KAPSABET", "SP-PRUNUS", 1200, 180, "Register carry-over", { seedbedId: "SB-KC-A", seedBatchId: "BATCH-2026-01", direction: "IN" }]),
  txn(["TX-0002", "PROPAGATION", "NUR-KAPSABET", "SP-PRUNUS", 800, 150, "Nursery propagation", { seedbedId: "SB-KC-A", seedBatchId: "BATCH-2026-01", direction: "IN" }]),
  txn(["TX-0003", "SALE", "NUR-KAPSABET", "SP-PRUNUS", 300, 60, "Sale to Kaptagat FMG", { direction: "OUT", destination: "Kaptagat Forest Users Association" }]),
  txn(["TX-0004", "MORTALITY", "NUR-KAPSABET", "SP-PRUNUS", 40, 45, "Dry spell in hardening area", { seedbedId: "SB-KC-C", direction: "OUT" }]),
  txn(["TX-0005", "DONATION", "NUR-KAPSABET", "SP-PRUNUS", 200, 30, "Donation to Chepterit primary", { direction: "OUT", destination: "Chepterit Primary School" }]),
  txn(["TX-0006", "PLANTING", "NUR-KAPSABET", "SP-PRUNUS", 260, 20, "Chepterit boundary planting", { direction: "OUT", destination: "Chepterit boundary" }]),

  // Kapsabet — Vitex
  txn(["TX-0007", "OPENING_STOCK", "NUR-KAPSABET", "SP-VITEX", 1500, 180, "Register carry-over", { seedbedId: "SB-KC-B", direction: "IN" }]),
  txn(["TX-0008", "PROPAGATION", "NUR-KAPSABET", "SP-VITEX", 1500, 140, "Nursery propagation", { seedbedId: "SB-KC-B", direction: "IN" }]),
  txn(["TX-0009", "SALE", "NUR-KAPSABET", "SP-VITEX", 250, 55, "Sale to Nandi County horticulture", { direction: "OUT", destination: "Nandi County Government" }]),
  txn(["TX-0010", "MORTALITY", "NUR-KAPSABET", "SP-VITEX", 30, 40, "Aphid outbreak", { seedbedId: "SB-KC-B", direction: "OUT" }]),
  txn(["TX-0011", "PLANTING", "NUR-KAPSABET", "SP-VITEX", 200, 18, "Kapsabet water pan planting", { direction: "OUT", destination: "Kapsabet water pan" }]),

  // Kapsabet — Croton
  txn(["TX-0012", "PROPAGATION", "NUR-KAPSABET", "SP-CROTON", 1000, 110, "Nursery propagation", { seedbedId: "SB-KC-B", seedBatchId: "BATCH-2026-02", direction: "IN" }]),
  txn(["TX-0013", "SALE", "NUR-KAPSABET", "SP-CROTON", 100, 25, "Sale to local dairy farmers", { seedbedId: "SB-KC-C", direction: "OUT" }]),
  txn(["TX-0014", "MORTALITY", "NUR-KAPSABET", "SP-CROTON", 20, 22, "Transplant shock", { seedbedId: "SB-KC-C", direction: "OUT" }]),
  txn(["TX-0015", "DONATION", "NUR-KAPSABET", "SP-CROTON", 50, 12, "JazaMiti riparian support", { seedbedId: "SB-KC-C", direction: "OUT", destination: "Kaptagat riparian group" }]),

  // Kaptagat — Dombeya
  txn(["TX-0016", "OPENING_STOCK", "NUR-KAPTAGAT", "SP-DOMBEYA", 500, 170, "Register carry-over", { seedbedId: "SB-KT-A", direction: "IN" }]),
  txn(["TX-0017", "ACQUISITION", "NUR-KAPTAGAT", "SP-DOMBEYA", 600, 100, "Seed purchase from KFS", { seedbedId: "SB-KT-A", seedBatchId: "BATCH-2026-03", direction: "IN" }]),
  txn(["TX-0018", "PROPAGATION", "NUR-KAPTAGAT", "SP-DOMBEYA", 400, 75, "Nursery propagation", { seedbedId: "SB-KT-A", seedBatchId: "BATCH-2026-03", direction: "IN" }]),
  txn(["TX-0019", "MORTALITY", "NUR-KAPTAGAT", "SP-DOMBEYA", 15, 35, "Water stress", { seedbedId: "SB-KT-A", direction: "OUT" }]),
  txn(["TX-0020", "PLANTING", "NUR-KAPTAGAT", "SP-DOMBEYA", 350, 15, "Kaptagat river reserve", { direction: "OUT" }]),

  // Kaptagat — Grevillea
  txn(["TX-0021", "OPENING_STOCK", "NUR-KAPTAGAT", "SP-GREVILLEA", 600, 170, "Register carry-over", { seedbedId: "SB-KT-A", direction: "IN" }]),
  txn(["TX-0022", "SALE", "NUR-KAPTAGAT", "SP-GREVILLEA", 100, 40, "Sale to Kaptagat dairy group", { direction: "OUT" }]),
  txn(["TX-0023", "DONATION", "NUR-KAPTAGAT", "SP-GREVILLEA", 100, 10, "School feeding hedge", { direction: "OUT" }]),

  // Kaptagat — Terminalia
  txn(["TX-0024", "PROPAGATION", "NUR-KAPTAGAT", "SP-TERMINALIA", 900, 65, "Nursery propagation", { seedbedId: "SB-KT-A", direction: "IN" }]),
  txn(["TX-0025", "MORTALITY", "NUR-KAPTAGAT", "SP-TERMINALIA", 25, 28, "Fungal infection", { seedbedId: "SB-KT-A", direction: "OUT" }]),
  txn(["TX-0026", "PLANTING", "NUR-KAPTAGAT", "SP-TERMINALIA", 300, 8, "Kaptagat community woodlot", { direction: "OUT" }]),

  // Cross-nursery transfer
  txn(["TX-0027", "TRANSFER_OUT", "NUR-KAPSABET", "SP-VITEX", 100, 14, "Transfer to Kaptagat nursery", { direction: "OUT", destination: "NUR-KAPTAGAT" }]),
  txn(["TX-0028", "TRANSFER_IN", "NUR-KAPTAGAT", "SP-VITEX", 100, 14, "Transfer from Kapsabet nursery", { direction: "IN", source: "NUR-KAPSABET" }]),

  // Pending verification entries
  txn(["TX-0029", "PROPAGATION", "NUR-KAPSABET", "SP-CROTON", 250, 5, "Second nursery round", { seedbedId: "SB-KC-B", seedBatchId: "BATCH-2026-02", direction: "IN", verificationStatus: "SUBMITTED" }]),
  txn(["TX-0030", "SALE", "NUR-KAPTAGAT", "SP-TERMINALIA", 40, 3, "Sale pending verification", { direction: "OUT", verificationStatus: "SUBMITTED" }]),
];

const sales: Sale[] = [
  {
    id: "SALE-0001",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-PRUNUS",
    quantity: 300,
    date: dayOf(60),
    buyerName: "Kaptagat Forest Users Association",
    buyerContact: "+254722000111",
    unitPrice: 120,
    currency: "KES",
    paymentStatus: "PAID",
    purpose: "Enrichment planting",
    destination: "Kaptagat forest",
    recordedBy: "Achieng",
    createdAt: ago(60),
  },
  {
    id: "SALE-0002",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-VITEX",
    quantity: 250,
    date: dayOf(55),
    buyerName: "Nandi County Government",
    buyerContact: "county@nandi.go.ke",
    unitPrice: 80,
    currency: "KES",
    paymentStatus: "PARTIALLY_PAID",
    purpose: "Water pan greening",
    destination: "Kapsabet water pan",
    recordedBy: "Achieng",
    createdAt: ago(55),
  },
  {
    id: "SALE-0003",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-CROTON",
    quantity: 100,
    date: dayOf(25),
    buyerName: "Kapsabet Dairy Cooperative",
    buyerContact: "+254733000222",
    unitPrice: 90,
    currency: "KES",
    paymentStatus: "PENDING",
    purpose: "Fodder",
    destination: "Kapsabet",
    recordedBy: "Kiptoo",
    createdAt: ago(25),
  },
  {
    id: "SALE-0004",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-GREVILLEA",
    quantity: 100,
    date: dayOf(40),
    buyerName: "Kaptagat Dairy Group",
    buyerContact: "+254711000333",
    unitPrice: 60,
    currency: "KES",
    paymentStatus: "PAID",
    purpose: "Fodder hedge",
    destination: "Kaptagat",
    recordedBy: "Kiptoo",
    createdAt: ago(40),
  },
];

const donations: Donation[] = [
  {
    id: "DON-0001",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-PRUNUS",
    quantity: 200,
    date: dayOf(30),
    recipientName: "Chepterit Primary School",
    recipientContact: "+254712000444",
    purpose: "School shade trees",
    plantingLocation: "Chepterit Primary compound",
    recordedBy: "Achieng",
    createdAt: ago(30),
  },
  {
    id: "DON-0002",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-CROTON",
    quantity: 50,
    date: dayOf(12),
    recipientName: "Kaptagat Riparian Group",
    recipientContact: "+254722000555",
    purpose: "Riparian buffer support",
    plantingLocation: "Kaptagat river reserve",
    programId: "PROG-JAZAMITI",
    recordedBy: "Kiptoo",
    createdAt: ago(12),
  },
  {
    id: "DON-0003",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-GREVILLEA",
    quantity: 100,
    date: dayOf(10),
    recipientName: "Kaptagat School Feeding Programme",
    recipientContact: "+254711000666",
    purpose: "Boundary hedge",
    plantingLocation: "Kaptagat ECD centre",
    recordedBy: "Kiptoo",
    createdAt: ago(10),
  },
];

const transfers: Transfer[] = [
  {
    id: "TRF-0001",
    sourceNurseryId: "NUR-KAPSABET",
    destinationNurseryId: "NUR-KAPTAGAT",
    destinationProject: "Kaptagat community woodlot",
    speciesId: "SP-VITEX",
    quantity: 100,
    date: dayOf(14),
    reason: "Kaptagat nursery short of Vitex for the woodlot",
    senderName: "Achieng",
    receiverName: "Kiptoo",
    createdAt: ago(14),
  },
];

const plantingEvents: PlantingEvent[] = [
  {
    id: "PLT-0001",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-PRUNUS",
    quantityPlanted: 260,
    date: dayOf(20),
    siteName: "Chepterit boundary",
    latitude: -0.2041,
    longitude: 35.1044,
    siteDescription: "Eastern boundary of Chepterit forest, mixed with existing shrubs.",
    responsibleGroup: "Chepterit Youth Group",
    landowner: "Chepterit Forest Owners",
    status: "MONITORING",
    recordedBy: "Achieng",
    createdAt: ago(20),
  },
  {
    id: "PLT-0002",
    nurseryId: "NUR-KAPSABET",
    speciesId: "SP-VITEX",
    quantityPlanted: 200,
    date: dayOf(18),
    siteName: "Kapsabet water pan",
    latitude: -0.2038,
    longitude: 35.1008,
    siteDescription: "Perimeter of the community water pan, full sun.",
    responsibleGroup: "Kapsabet Water Committee",
    landowner: "Nandi Water Company",
    status: "MONITORING",
    programId: "PROG-JAZAMITI",
    recordedBy: "Kiptoo",
    createdAt: ago(18),
  },
  {
    id: "PLT-0003",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-DOMBEYA",
    quantityPlanted: 350,
    date: dayOf(15),
    siteName: "Kaptagat river reserve",
    latitude: -0.3162,
    longitude: 35.0131,
    siteDescription: "Riverine strip, seasonally inundated.",
    responsibleGroup: "Kaptagat Riparian Group",
    landowner: "Kaptagat Village Council",
    programId: "PROG-JAZAMITI",
    status: "MONITORING",
    recordedBy: "Kiptoo",
    createdAt: ago(15),
  },
  {
    id: "PLT-0004",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-TERMINALIA",
    quantityPlanted: 300,
    date: dayOf(8),
    siteName: "Kaptagat community woodlot",
    latitude: -0.3148,
    longitude: 35.0101,
    siteDescription: "New woodlot, 3m spacing, contour planting.",
    responsibleGroup: "Kaptaget Youth Group",
    landowner: "Kaptagat Village Council",
    status: "IN_PROGRESS",
    recordedBy: "Kiptoo",
    createdAt: ago(8),
  },
];

const survivalObservations: SurvivalObservation[] = [
  {
    id: "OBS-0001",
    plantingEventId: "PLT-0001",
    date: dayOf(13),
    observerName: "Achieng",
    assessed: 260,
    surviving: 246,
    dead: 11,
    missing: 3,
    damaged: 0,
    causeOfLoss: "Transplant shock during dry spell",
    latitude: -0.2041,
    longitude: 35.1044,
    createdAt: ago(13),
  },
  {
    id: "OBS-0002",
    plantingEventId: "PLT-0001",
    date: dayOf(3),
    observerName: "Chebet",
    assessed: 246,
    surviving: 238,
    dead: 6,
    missing: 2,
    damaged: 0,
    causeOfLoss: "Weeds and dry spell",
    latitude: -0.2041,
    longitude: 35.1044,
    createdAt: ago(3),
  },
  {
    id: "OBS-0003",
    plantingEventId: "PLT-0002",
    date: dayOf(10),
    observerName: "Kiptoo",
    assessed: 200,
    surviving: 184,
    dead: 12,
    missing: 4,
    damaged: 0,
    causeOfLoss: "Water pan edge exposure",
    latitude: -0.2038,
    longitude: 35.1008,
    createdAt: ago(10),
  },
  {
    id: "OBS-0004",
    plantingEventId: "PLT-0003",
    date: dayOf(7),
    observerName: "Kiptoo",
    assessed: 350,
    surviving: 337,
    dead: 9,
    missing: 4,
    damaged: 0,
    causeOfLoss: "Seasonal flooding",
    latitude: -0.3162,
    longitude: 35.0131,
    createdAt: ago(7),
  },
];

const activities: Activity[] = [
  {
    id: "ACT-0001",
    activityType: "PROPAGATION",
    nurseryId: "NUR-KAPSABET",
    seedbedId: "SB-KC-B",
    speciesId: "SP-CROTON",
    seedBatchId: "BATCH-2026-02",
    quantity: 250,
    date: dayOf(5),
    recordedBy: "Kiptoo",
    notes: "Second round pricking out after the first batch was potted.",
    status: "SUBMITTED",
    createdAt: ago(5),
    updatedAt: ago(5),
  },
  {
    id: "ACT-0002",
    activityType: "SALE",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-TERMINALIA",
    quantity: 40,
    date: dayOf(3),
    recordedBy: "Kiptoo",
    notes: "Sale to a local woodcraft group, awaiting verification.",
    status: "SUBMITTED",
    createdAt: ago(3),
    updatedAt: ago(3),
  },
  {
    id: "ACT-0003",
    activityType: "MORTALITY",
    nurseryId: "NUR-KAPTAGAT",
    seedbedId: "SB-KT-A",
    speciesId: "SP-TERMINALIA",
    quantity: 25,
    date: dayOf(28),
    recordedBy: "Kiptoo",
    notes: "Fungal infection in the western corner of the bed.",
    status: "VERIFIED",
    createdAt: ago(28),
    updatedAt: ago(27),
  },
  {
    id: "ACT-0004",
    activityType: "HARDENING",
    nurseryId: "NUR-KAPSABET",
    seedbedId: "SB-KC-C",
    speciesId: "SP-CROTON",
    quantity: 300,
    date: dayOf(21),
    recordedBy: "Achieng",
    notes: "Two-week hardening before the community distribution.",
    status: "NEEDS_CORRECTION",
    createdAt: ago(21),
    updatedAt: ago(19),
  },
  {
    id: "ACT-0005",
    activityType: "PEST_MANAGEMENT",
    nurseryId: "NUR-KAPSABET",
    seedbedId: "SB-KC-B",
    speciesId: "SP-VITEX",
    quantity: 400,
    date: dayOf(41),
    recordedBy: "Achieng",
    notes: "Aphid outbreak treated with neem extract.",
    status: "VERIFIED",
    createdAt: ago(41),
    updatedAt: ago(40),
  },
  {
    id: "ACT-0006",
    activityType: "DONATION",
    nurseryId: "NUR-KAPTAGAT",
    speciesId: "SP-GREVILLEA",
    quantity: 100,
    date: dayOf(10),
    recordedBy: "Kiptoo",
    notes: "Hedge seedlings for the Kaptagat ECD centre.",
    status: "VERIFIED",
    createdAt: ago(10),
    updatedAt: ago(9),
  },
  {
    id: "ACT-0007",
    activityType: "WEEDING",
    nurseryId: "NUR-KAPSABET",
    seedbedId: "SB-KC-A",
    speciesId: "SP-PRUNUS",
    quantity: 900,
    date: dayOf(16),
    recordedBy: "Achieng",
    notes: "Two days of weeding before the hardening move.",
    status: "DRAFT",
    createdAt: ago(2),
    updatedAt: ago(1),
  },
];

const programs: Program[] = [
  {
    id: "PROG-JAZAMITI",
    name: "JazaMiti",
    organisation: "Kenya Forest Service",
    description:
      "National greening programme supporting community nurseries and tree planting.",
    programType: "GOVERNMENT",
    startDate: dayOf(400),
    endDate: dayOf(-300),
    contactName: "Nandi County Forester",
    status: "ACTIVE",
    isPublic: true,
    notes: "Requires monthly seedling distribution reports.",
  },
  {
    id: "PROG-KAI-IMPACT",
    name: "KAI Internal Impact Tracking",
    organisation: "KAI Nuvari",
    description: "Internal tracking of CFA nursery production and survival.",
    programType: "INTERNAL",
    startDate: dayOf(300),
    contactName: "CFA Secretariat",
    status: "ACTIVE",
    isPublic: false,
  },
  {
    id: "PROG-COMM-WOODLOT",
    name: "Community Woodlot Project",
    organisation: "Kaptagat Village Council",
    description: "Village woodlot establishment using nursery seedlings.",
    programType: "COMMUNITY",
    startDate: dayOf(120),
    contactName: "Village Secretary",
    status: "ACTIVE",
    isPublic: true,
  },
];

const evidence: Evidence[] = [
  {
    id: "EVD-0001",
    entityType: "ACTIVITY",
    entityId: "ACT-0001",
    kind: "PHOTO",
    fileName: "seedbed-b-pricking.jpg",
    fileType: "image/jpeg",
    reference: "camera://2026/seedbed-b-pricking.jpg",
    contentHash: "fp:3f1c9a77e2b4",
    uploadedBy: "Kiptoo",
    captureDate: dayOf(5),
    latitude: -0.2027,
    longitude: 35.1021,
    visibility: "CFA_ONLY",
    consentStatus: "GRANTED",
    verificationStatus: "SUBMITTED",
    createdAt: ago(5),
  },
  {
    id: "EVD-0002",
    entityType: "ACTIVITY",
    entityId: "ACT-0002",
    kind: "RECEIPT",
    fileName: "woodcraft-receipt.pdf",
    fileType: "application/pdf",
    reference: "receipt://2026/woodcraft-receipt.pdf",
    contentHash: "fp:9ab24c10d5e7",
    uploadedBy: "Kiptoo",
    captureDate: dayOf(3),
    visibility: "VERIFIER_ONLY",
    consentStatus: "GRANTED",
    verificationStatus: "SUBMITTED",
    createdAt: ago(3),
  },
  {
    id: "EVD-0003",
    entityType: "ACTIVITY",
    entityId: "ACT-0003",
    kind: "PHOTO",
    fileName: "terminalia-fungal.jpg",
    fileType: "image/jpeg",
    reference: "camera://2026/terminalia-fungal.jpg",
    contentHash: "fp:77d0e2aa14c8",
    uploadedBy: "Kiptoo",
    captureDate: dayOf(28),
    latitude: -0.3155,
    longitude: 35.0112,
    visibility: "CFA_ONLY",
    consentStatus: "GRANTED",
    verificationStatus: "VERIFIED",
    createdAt: ago(28),
  },
  {
    id: "EVD-0004",
    entityType: "ACTIVITY",
    entityId: "ACT-0006",
    kind: "ATTENDANCE",
    fileName: "handover-attendance.pdf",
    fileType: "application/pdf",
    reference: "file://2026/handover-attendance.pdf",
    contentHash: "fp:c41b7e0d9a32",
    uploadedBy: "Kiptoo",
    captureDate: dayOf(10),
    visibility: "CFA_ONLY",
    consentStatus: "GRANTED",
    verificationStatus: "VERIFIED",
    createdAt: ago(10),
  },
];

const verifications: Verification[] = [
  {
    id: "VER-0001",
    entityType: "ACTIVITY",
    entityId: "ACT-0003",
    submittedBy: "Kiptoo",
    submittedAt: ago(27),
    reviewedBy: "Mwangi",
    reviewedAt: ago(26),
    method: "PHOTO_REVIEW",
    evidenceIds: ["EVD-0003"],
    notes: "Photo matches the bed location and the affected corner.",
    decision: "APPROVED",
    previousStatus: "SUBMITTED",
    newStatus: "VERIFIED",
  },
  {
    id: "VER-0002",
    entityType: "ACTIVITY",
    entityId: "ACT-0006",
    submittedBy: "Kiptoo",
    submittedAt: ago(9),
    reviewedBy: "Mwangi",
    reviewedAt: ago(9),
    method: "DOCUMENT_REVIEW",
    evidenceIds: ["EVD-0004"],
    notes: "Attendance sheet signed by the recipient.",
    decision: "APPROVED",
    previousStatus: "SUBMITTED",
    newStatus: "VERIFIED",
  },
  {
    id: "VER-0003",
    entityType: "ACTIVITY",
    entityId: "ACT-0004",
    submittedBy: "Achieng",
    submittedAt: ago(20),
    reviewedBy: "Mwangi",
    reviewedAt: ago(19),
    method: "FIELD_VISIT",
    evidenceIds: [],
    notes: "Quantity on the form does not match the bed count. Please recount and resubmit.",
    decision: "CORRECTIONS_REQUESTED",
    previousStatus: "SUBMITTED",
    newStatus: "NEEDS_CORRECTION",
  },
];

export function buildSeedState(): CfaState {
  return {
    cfa: {
      id: "CFA-KE-042",
      name: "Kapsabet Forest Association",
      registrationNumber: "CFA/NKE/2019/042",
      country: "Kenya",
      county: "Nandi",
      subCounty: "Kapsabet",
      ward: "Kapsabet",
      community: "Chepterit",
      description:
        "Community forest association managing the Chepterit forest block, two nurseries, and community woodlots in Nandi County.",
      mission:
        "Restore degraded forest blocks, support member livelihoods, and keep an auditable record of every seedling the association produces and plants.",
      contactName: "Agnes Chebet",
      contactPhone: "+254700000001",
      contactEmail: "kapsabetcfa@example.org",
      latitude: -0.2027,
      longitude: 35.1021,
      establishedAt: dayOf(2200),
      leaderName: "Agnes Chebet",
      status: "ACTIVE",
      isPublic: true,
    },
    role: "ADMIN",
    currentUser: "Agnes Chebet",
    nurseries,
    seedbeds,
    species,
    batches,
    transactions,
    activities,
    plantingEvents,
    survivalObservations,
    sales,
    donations,
    transfers,
    programs,
    evidence,
    verifications,
    auditLog: [
      {
        id: "AUD-0001",
        event: "REPORT_GENERATED",
        actor: "Agnes Chebet",
        details: "Nursery production report for Kapsabet Central Nursery.",
        at: ago(9),
      },
      {
        id: "AUD-0002",
        event: "ACTIVITY_VERIFIED",
        entityType: "ACTIVITY",
        entityId: "ACT-0006",
        actor: "Mwangi",
        details: "Donation verified by document review.",
        at: ago(9),
      },
      {
        id: "AUD-0003",
        event: "EVIDENCE_UPLOADED",
        entityType: "ACTIVITY",
        entityId: "ACT-0002",
        actor: "Kiptoo",
        details: "Receipt uploaded for the Terminalia sale.",
        at: ago(3),
      },
    ],
  };
}
